# Site settings
title: "Riccardo Scalco"
email: riccardo@riccardoscalco.it
description: Riccardo Scalco creates graphical representations of data.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://riccardoscalco.it" # the base hostname & protocol for your site
twitter_username: eidogram
github_username:  riccardoscalco
keywords: "web design, frontend, data visualization, big data, data science, infographics"

# Build settings
markdown: kramdown

defaults:
  - scope:
      path: "assets/frags"
    values:
      image: true
